'use client'
import { useCallback, useEffect, useState } from 'react'
import { apiGet, apiPatch, getStoredUser } from '@/lib/api'

export default function Terminals(){
  const [items,setItems]=useState<any[]>([]), [serverTime,setServerTime]=useState(''), [loading,setLoading]=useState(true), [error,setError]=useState('')
  const owner=getStoredUser()?.role==='owner'
  const load=useCallback(async()=>{try{const data=await apiGet('/terminals');setItems(data.items||[]);setServerTime(data.server_time);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}},[])
  useEffect(()=>{load();const timer=setInterval(load,20000);return()=>clearInterval(timer)},[load])
  const rename=async(t:any)=>{const name=prompt('اسم الجهاز:',t.name);if(!name)return;await apiPatch(`/terminals/${t.id}`,{name});load()}
  const revoke=async(t:any)=>{if(!confirm(t.is_revoked?'إعادة تفعيل الجهاز؟':'إلغاء صلاحية هذا الجهاز؟'))return;await apiPatch(`/terminals/${t.id}`,{revoked:!t.is_revoked});load()}
  return <div className="space-y-4"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold">أجهزة نقاط البيع</h1><p className="text-sm text-gray-500">الحالة تتحدث كل 20 ثانية؛ الجهاز يعتبر غير متصل بعد 90 ثانية دون heartbeat.</p></div><button className="btn-secondary" onClick={load}>تحديث</button></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="card"><div className="text-sm text-gray-500">إجمالي الأجهزة</div><div className="text-2xl font-bold">{items.length}</div></div><div className="card"><div className="text-sm text-gray-500">متصل</div><div className="text-2xl font-bold text-green-700">{items.filter(x=>x.online).length}</div></div><div className="card"><div className="text-sm text-gray-500">غير متصل</div><div className="text-2xl font-bold text-gray-600">{items.filter(x=>!x.online).length}</div></div></div>
    <div className="card overflow-auto">{error&&<div className="text-red-700 mb-3">{error}</div>}<table><thead><tr><th>الحالة</th><th>الجهاز</th><th>الفرع</th><th>آخر اتصال</th><th>آخر مزامنة</th><th>حالة المزامنة</th><th>معلق</th><th>الإصدار</th><th></th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td><span className={`status-dot ${t.online?'bg-green-500':'bg-gray-400'}`}/>{t.is_revoked?'ملغي':t.online?'متصل':'غير متصل'}</td><td><b>{t.name}</b><div className="text-xs text-gray-500">{t.terminal_code}</div></td><td>{t.branch?.name_ar||t.branch?.code}</td><td>{t.last_seen_at?new Date(t.last_seen_at).toLocaleString('ar-EG'):'لم يتصل'}</td><td>{t.last_sync_at?new Date(t.last_sync_at).toLocaleString('ar-EG'):'لم تتم'}</td><td className={t.last_sync_status==='error'?'text-red-700':''}>{t.last_sync_status}{t.last_error&&<div className="text-xs max-w-xs truncate" title={t.last_error}>{t.last_error}</div>}</td><td>{t.pending_count}</td><td>{t.app_version||'—'}</td><td><button className="text-blue-700 ml-2" onClick={()=>rename(t)}>تسمية</button>{owner&&<button className="text-red-700" onClick={()=>revoke(t)}>{t.is_revoked?'تفعيل':'إلغاء'}</button>}</td></tr>)}{!loading&&!items.length&&<tr><td colSpan={9} className="text-center text-gray-500 py-8">لم يسجل أي جهاز POS نفسه بعد. افتح POS وسجل الدخول ليظهر هنا.</td></tr>}{loading&&<tr><td colSpan={9} className="text-center py-8">جارٍ التحميل…</td></tr>}</tbody></table><div className="text-xs text-gray-500 mt-3">وقت الخادم: {serverTime?new Date(serverTime).toLocaleString('ar-EG'):'—'}</div></div>
  </div>
}
